### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by wolfgold** [kyle0418/K-Alarm#2]
Hi kyle:
This Alarm is simple and nice. But I still have some advice  to make the software more better. Firstly,what I think is that add button could be  placed under the item you list.
Secondly,if i chose the item to work,perhaps the item can change the background color to make it eyecoming.
regrads 
bookdrip

**Comment by kyle0418** [comment]
First, thanks for your feedback. Do you mean modify the UI like this?
![20190626135202](https://user-images.githubusercontent.com/25261738/60154376-ba607a00-9819-11e9-8362-503e3a58f184.jpg)

**Comment by wolfgold** [comment]
> First, thanks for your feedback. Do you mean modify the UI like this?
> ![20190626135202](https://user-images.githubusercontent.com/25261738/60154376-ba607a00-9819-11e9-8362-503e3a58f184.jpg)
Yes.The button could move autoly by adding item.

**Comment by kyle0418** [comment]
Implemented this feature, please check it

**Comment by wolfgold** [comment]
When I added to Maxium items,the add button disappered.Though I deleted items, add button is still not appear.
![image](https://user-images.githubusercontent.com/28920278/60158146-18de2600-9823-11e9-8763-183b2c38f3d9.png)

**Comment by kyle0418** [comment]
Yes, I have noticed it, modifying... 2333

**Comment by kyle0418** [comment]
I have reset the location of "AddButton". As to out of bounds, it does not occur on my PC. So, I assume it may be related to "DPI". I have modify the mode to "DPI". Please help to check if it works fine.

**Comment by wolfgold** [comment]
work well!

**Comment by wolfgold** [comment]
when I set the time,the set dialog should be closed.That may be more better.

**Comment by kyle0418** [comment]
Good idea! Done and please check it.

**Comment by wolfgold** [comment]
It's OK!
